language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync
 
script:
  - xbuild ./src/DG.BotWorld.sln /property:"Configuration=OSX;Platform=Any CPU"
  - nunit-console ./src/DG.BotWorld.Hosting.UnitTests/bin/Release/DG.BotWorld.Hosting.UnitTests.dll
